stages:
  - build_next
  - deploy_next

build-next:
  stage: build_next
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Building Next.js"
    - docker compose build next
    - docker compose push next
  tags:
    - production
  only:
    - main

deploy-next:
  stage: deploy_next
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd /var/www/haohub
    - echo "Pulling images..."
    - docker compose pull next
    - docker compose up -d next --remove-orphans
  environment:
    name: production
    url: https://$DOMAIN
  tags:
    - production
  only:
    - main
