stages:
  - build
  - deploy
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd next
    - docker build
      -t $CI_REGISTRY_IMAGE/nextjs:latest .
    - docker push $CI_REGISTRY_IMAGE/nextjs:latest

    # При необходимости можно добавить сборку Drupal
    - cd ../drupal
    - docker build -t $CI_REGISTRY_IMAGE/drupal:latest .
    - docker push $CI_REGISTRY_IMAGE/drupal:latest
  only:
    - main
deploy:
  stage: deploy
  script:
    - cd /var/www/haohub
    - docker-compose pull
    - docker-compose up -d
  only:
    - main
  environment:
    name: production
    url: https://$DOMAIN
  tags:
    - production
