services:
  nextjs:
    build:
      context: ./next
      args:
        - NEXT_PUBLIC_DRUPAL_BASE_URL=http://host.docker.internal:8080
    container_name: next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_DRUPAL_BASE_URL=${DRUPAL_BASE_URL}
      - NEXT_IMAGE_DOMAIN=drupal
      - DRUPAL_CLIENT_ID=${DRUPAL_CLIENT_ID}
      - DRUPAL_CLIENT_SECRET=${DRUPAL_CLIENT_SECRET}
      - DRUPAL_REVALIDATE_SECRET=${DRUPAL_REVALIDATE_SECRET}
    networks:
      - drupal_network

networks:
  drupal_network:
    external: true
