version: "3.8"

services:
  nextjs:
    build:
      context: ./next
    container_name: next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_DRUPAL_BASE_URL=http://drupal
      - NEXT_IMAGE_DOMAIN=drupal
      - DRUPAL_CLIENT_ID=${DRUPAL_CLIENT_ID}
      - DRUPAL_CLIENT_SECRET=${DRUPAL_CLIENT_SECRET}
      - DRUPAL_REVALIDATE_SECRET=${DRUPAL_REVALIDATE_SECRET}
    networks:
      - drupal_network
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  drupal_network:
    external: true
